# -*- coding: utf-8 -*-
"""Prototipo_Servidor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1syciHPOf6fxZrpqmBA7JzHTf6Q58Le3_
"""

!pip install django

!django-admin startproject myproject1

# Commented out IPython magic to ensure Python compatibility.
# %cd myproject1
!python manage.py startapp myapp

!cat myproject1/urls.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile myproject1/urls.py
# from django.contrib import admin
# from django.urls import path
# 
# from myapp.views import hello
# 
# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('', hello),
# ]

!cat myapp/views.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile myapp/views.py
# from django.http import HttpResponse
# 
# def hello(request):
#     return HttpResponse("Olá, mundo!")

!python manage.py migrate

!python manage.py runserver 8000